### ISSUE TITLE
Should warn when using a device name that doesn't belong to the vendor id

### ISSUE THREAD

**Issue by forivall** [dslackw/USBdev#2]
I see that you fallback to searching all device names if there's no matching id for the vendor id. However, there should be a warning when you do so. For example, the keyboard that I'm working on a driver for reports
```
1: 'Genesys Logic, Inc. miniVigor 128 ISDN TA [HFC-S]'
2: 'SiGma Micro WL-160g 802.11g Wireless Adapter [Envara WiND512]'
```

**Comment by dslackw** [comment]
Thank you for this report. It seems the devices I've tried have matching vendor_name with device_name so no error occurred.
We will try to resolve as soon as...

**Comment by dslackw** [comment]
Hi @forivall,

Let me know if new v10.12.20150331 solve #1 and #2 issues.
Thank you.
dslackw

**Comment by forivall** [comment]
looks good
```
❯ python2 usbdev/main.py
Plugin USB device(s) now ...................................................Done
Found: Vendor(s)             Device(s)
1:     Genesys Logic, Inc.   Not found
2:     SiGma Micro           Not found
```
